# Generated by Django 3.1.2 on 2020-11-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pazienti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paziente', models.CharField(blank=True, default='DEFAULT VALUE', max_length=200, null=True, verbose_name='paziente')),
                ('data_nascita_paziente', models.DateField(blank=True, null=True)),
                ('nome_proprietario', models.CharField(blank=True, max_length=200, null=True, verbose_name='nome proprietario')),
                ('cognome_proprietario', models.CharField(blank=True, max_length=200, null=True, verbose_name='cognome proprietario')),
            ],
            options={
                'ordering': ['paziente'],
            },
        ),
    ]
